services:

  postgres:
    build:
      context: ./postgres
    container_name: postgres18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

  web:
    build:
      context: ./nginx
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge